### ISSUE TITLE
When README.md is missing a cryptic message is displayed

### ISSUE THREAD

**Issue by sigmavirus24** [ansible/galaxy-issues#103]
See https://github.com/ansible/ansible/issues/13845 for a little more context.

Some projects may attempt to use some other extension than `md` (e.g., `rst`) for their README which GitHub supports. When you attempt to add the role, however, instead of a helpful error message you instead receive:

```
Error: FAILED: Failed to update the specified role's fields. Please retry the import in a few minutes. If you continue to receive a failure, please contact support. Error was: global name 'role' is not defined
```

This should be improved to help users determine why their addition/import failed.

**Comment by chouseknecht** [comment]
This is addressed in Galaxy 2.0.  See screen shot below:

![new_import_screen](https://cloud.githubusercontent.com/assets/1282865/12470209/612b1290-bfc0-11e5-816c-2e5e4630b1e7.png)

**Comment by sigmavirus24** [comment]
:+1: looks great. Now can we off-load README parsing/display on GitHub's README API so people can use any README format they like so long as GitHub renders the HTML for you?

**Comment by pabelanger** [comment]
Yes, please don't force me to use .md, when I can be using .rst format. Since all my documentation is done with sphinx, moving to .md is a deal break for uploading roles to galaxy.

**Comment by sigmavirus24** [comment]
But seriously, since Galaxy is already rather tied to GitHub, just use https://developer.github.com/v3/repos/contents/#get-the-readme

**Comment by pabelanger** [comment]
+1

**Comment by chouseknecht** [comment]
We do not store HTML version of README. We store the raw contents of the README and convert it to HTML on request.

Instead of looking specifically for README.md, switched the import process to use get_readme() method on the repo object (pygithub) which performs "GET /repos/:owner/:repo/readme". It then inspects the name property looking for either a .md or.rst extension to determine the readme_type attribute. 

When a request is received for the README the API converts the contents using either markdown or docutils.parse_string depending on the readme_type. 

This is deployed at galaxy-qa.ansible.com. For testing pursposes forked:

https://github.com/pabelanger/ansible-role-jenkins

Imported into galaxy-qa, and results are here:

https://galaxy-qa.ansible.com/chouseknecht/jenkins-1/

Only thing I notice is that our parsing of restructured text might be slightly more strict than GitHub. In the above test the Package header received an h3 tag rather than h2 because the title underline is shorter than the text. You can see warning if run the raw text through rst2html5-tools (https://github.com/marianoguerra/rst2html5)

**Comment by sigmavirus24** [comment]
Cool. I'm not sure what GitHub uses to render rst files, but given their move away from Pygments for source code rendering, I bet it's a reinvented wheel in ruby.

**Comment by pabelanger** [comment]
Nice, looks good. If you are using python, sphinx can be used to render rst to html. That's why we use RST formatting.

Another option, would be to expose an option to the user to use external documentation. For example, I upload all of my docs to https://readthedocs.org/.  EG: https://ansible-role-nodepool.readthedocs.org/
