### ISSUE TITLE
"My roles" empty, roles are under a Github org

### ISSUE THREAD

**Issue by natefoo** [ansible/galaxy-issues#108]
[galaxyprojectdotorg](https://galaxy.ansible.com/galaxyprojectdotorg/) has 12 roles created before the switch to Github auth. Before the end of Galaxy internal auth, I linked the galaxyprojectdotorg Galaxy account to our Github bot account (@galaxybot) because my own Github account is already linked to another Ansible Galaxy account.

Our roles live underneath the [galaxyproject Github org](https://github.com/galaxyproject). If I click the 
"review and add your authorized organizations" link, Ansible Galaxy is an authorized application and has access to the galaxyproject org. Despite this (and after hitting the "refresh" icon numerous times in the last 18 hours), the "My roles" page does not show any of our repositories and only shows the message "No roles found in your public GitHub repositories."

**Comment by chouseknecht** [comment]
I see in our database that Galaxy username galaxyprojectdotorg is indeed linked to galaxybot, and the account id is 6421 (adding just for future reference).

Querying https://api.github.com/user/repos as GitHub user galaxybot, I get back the following list of repos:

galaxyproject/ansible-galaxy-extras
galaxyproject/cloudlaunch
galaxyproject/docker-galaxy-requirements
galaxyproject/galaxy
galaxyproject/planemo-machine
galaxyproject/pulsar
galaxyproject/starforge
martenson/galaxy

It looks like 'ansible-galaxy-extras' is intended to be a role, but it does not contain 'meta/main.yml'. All the other repos do not appear to be Ansible roles. 

That's how Galaxy figures out which roles to list on My Roles. It looks at https://api.github.com/user/repos as the user (in this case galaxybot) and inspects each repo for a 'meta/main.yml'.

It seems there are two solutions:
- Connect to Galaxy as a GitHub user that is a collaborator/team member on the role repos
- Or, grant collaborator/team member access to galaxybot so that the desired repos are included in the https://api.github.com/user/repos response for user galaxybot.

**Comment by natefoo** [comment]
Thanks for the explanation, I've granted the galaxybot user read access to all of our roles intended for Galaxy. The "My Roles" page now displays a "pulsating bars" icon, and clicking the "refresh" button just results in an endless spinner rather than quickly returning to the "no roles" message.

**Comment by chouseknecht** [comment]
Can you please give it another try.  When you log in we refresh your list of repos in the background. This can take a minute or two. It looked like our task manager was not in a good place, and the task to refresh your repos never executed. Tasks are executing normally now.

**Comment by natefoo** [comment]
Unfortunately, I'm still stuck in the same place.

**Comment by chouseknecht** [comment]
Nate,

I'm really sorry you're experiencing this problem, and I definitely want to help. Rather than us going back and forth within the confines of this issue/ticket, would it be possible for you to email me a phone number and a time when I can call you?  My email is chouse at ansible.com.

Please include a phone number and good time to give you a ring, and we will get this resolved.

Apologies for the inconvenience.

--Chris

**Comment by chouseknecht** [comment]
Adding additional error handling that should help us track this down.  Adding Milestone 2.0.1 and Bug label to at least get the error handling pushed to production.

**Comment by chouseknecht** [comment]
Somehow there were two GitHub accounts associate with Galaxy user account. We removed both, allowing Nate to associate the correct one. Problem solved.

**Comment by natefoo** [comment]
Thanks @chouseknecht!
