### ISSUE TITLE
Role import chokes on explicit dependency format

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy-issues#131]
Expressing role dependency in meta/main.yml using the following form causes an import error:

```
{ src: 'https://github.com/namespace/repo' }
```

Need to accommodate ALL the formats and handle correctly on role detail page.

**Comment by chouseknecht** [comment]
This may be dependent on the auto role install proposal.

**Comment by mikolak-net** [comment]
Would like to point out that this dependency approach is necessary when a role that's normally available on Galaxy has some critical unpublished changes (e.g. bugfixes). For example, I just had to redefine one of my roles' dependencies like so:

```
  - name: "knopki.locale"
    src: "git+https://github.com/knopki/ansible-locale.git"
    version: "a1232f836b5514c58da381d9479640e40d874906"
```

resulting in the following error message from Galaxy's importer:

>  Invalid role dependency: {'src': 'git+https://github.com/knopki/ansible-locale.git', 'version': 'a1232f836b5514c58da381d9479640e40d874906', 'name': 'knopki.locale'} (skipping) (error: 'role' keyword was not found in the role dictionary)
> Role dependency not found: {'src': 'git+https://github.com/knopki/ansible-locale.git', 'version': 'a1232f836b5514c58da381d9479640e40d874906', 'name': 'knopki.locale'} 

Please note that the `role` tag **must** be absent here, since its presence would force the latest version on Galaxy to be downloaded, in lieu of the provided source.

(Fortunately, the import actually fails in a graceful manner, and all the relevant information is actually updated)

**Comment by mikolak-net** [comment]
Would like to point out that this dependency approach is necessary when a role that's normally available on Galaxy has some critical unpublished changes (e.g. bugfixes). For example, I just had to redefine one of my roles' dependencies like so:

```
  - name: "knopki.locale"
    src: "git+https://github.com/knopki/ansible-locale.git"
    version: "a1232f836b5514c58da381d9479640e40d874906"
```

resulting in the following error message from Galaxy's importer:

>  Invalid role dependency: {'src': 'git+https://github.com/knopki/ansible-locale.git', 'version': 'a1232f836b5514c58da381d9479640e40d874906', 'name': 'knopki.locale'} (skipping) (error: 'role' keyword was not found in the role dictionary)
> Role dependency not found: {'src': 'git+https://github.com/knopki/ansible-locale.git', 'version': 'a1232f836b5514c58da381d9479640e40d874906', 'name': 'knopki.locale'} 


Please note that the `role` tag **must** be absent here, since its presence would force the latest version on Galaxy to be downloaded, in lieu of the provided source.

(Fortunately, the import actually fails in a graceful manner, and all the relevant information is actually updated)

**Comment by chouseknecht** [comment]
This is fixed in the latest release of Galaxy.
