### ISSUE TITLE
Unable to import role under personal user account instead of organization

### ISSUE THREAD

**Issue by tersmitten** [ansible/galaxy-issues#148]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
2.0.1.0
```
##### Ansible Configuration:

N/A
##### Environment:

N/A
##### Summary:

I'm unable to import (new) roles under my user account (tersmitten). In Github the role path is Oefenweb/ansible-fonts, but I want to import to tersmitten/fonts in galaxy. This is because all my other roles (+/- 100) are under tersmitten too. Is there any way to do that?

When I re-import old roles they import just fine under tersmitten.
##### Steps To Reproduce:

N/A
##### Expected Results:

Be able to specify or change the destination (user) on the galaxy side.
##### Actual Results:

Not able to specify or change the destination (user) on the galaxy side.

**Comment by chouseknecht** [comment]
This is intentional. Old roles (prior to Galaxy 2.0) remain in the existing namespace. New roles are imported into the namespace of the GitHub repo. 

What you can do is move the old roles from tersmitten to Oefenweb. The is accomplished by deleting the old role and re-importing it.

**Comment by tersmitten** [comment]
The old roles are all under Oefenweb (Github)

**Comment by tersmitten** [comment]
> What you can do is move the old roles from tersmitten to Oefenweb. The is accomplished by deleting the old role and re-importing it

that's a hell of a job and painful for all galaxy users that use my roles

**Comment by tersmitten** [comment]
Any examples of commands? I have all sorts of problems with `ansible-galaxy`?

**Comment by gregdek** [comment]
Sorry for the impact of this change, and we know it's painful to more prolific contributors like you, but we feel it was essential to make the linkage between the Github namespace and the Galaxy namespace more direct.

Note that there's no requirement for you to move these roles if you don't want to; we will continue to support the legacy namespaces. You can continue to reimport existing roles to these legacy namespaces -- and if you have a lot of users, you may want to do that rather than moving them all over. But new roles must be from a Github account that you are a member of.

**Comment by tersmitten** [comment]
How do I delete the old roles. do I use the cli or the web interface (or a combination)?

**Comment by chouseknecht** [comment]
You should be able to do it on the web interface as well as the client. 

On the web, under My Roles, you will see all of your repositories. Next to each repository is a toggle switch. Move it to the off position. You will be prompted to confirm deletion of the role. 

With the client run `ansible-galaxy delete --help` for details on how to delete roles.

--Chris

**Comment by tersmitten** [comment]
I'll give it a try, thanks
