### ISSUE TITLE
Unable to rename role

### ISSUE THREAD

**Issue by tersmitten** [ansible/galaxy-issues#150]
```
Starting import 8923: role_name=ansible-mailcatcher repo=Oefenweb/ansible-mailcatcher ref=
Retrieving Github repo Oefenweb/ansible-mailcatcher
Accessing branch: master
Parsing and validating meta/main.yml
Setting role name to mailcatcher
Parsing galaxy_tags
Parsing platforms
Adding dependencies
Parsing and validating README
Adding repo tags as role versions
Import completed
Status SUCCESS : warnings=0 errors=0
Error saving role: duplicate key value violates unique constraint "main_role_namespace_36aa1070a7d8dc70_uniq" DETAIL: Key (namespace, name)=(Oefenweb, mailcatcher) already exists.
```

Indeed `Oefenweb/mailcatcher` exists, but that's an incorrect (failed) import. On Github the repo is called `Oefenweb/ansible-mailcatcher`.

```
Starting import 8918: role_name=mailcatcher repo=Oefenweb/mailcatcher ref=
Retrieving Github repo Oefenweb/mailcatcher
Galaxy user tersmitten does not have access to repo Oefenweb/mailcatcher
```

Any way to fix this?

**Comment by chouseknecht** [comment]
It looks like you renamed the repo. The repo name was 'mailcatcher', and it was imported as role 'Oefenweb.mailcatcher'. There was something wrong, and the import failed. Then you presumably renamed the repo to 'ansible-mailcatcher' and imported it as Role 'Oefenweb.ansible-mailcatcher'. And then finally, you attempted to re-import the same repo with the name 'mailcatcher', which collided with the old, invalid 'mailcatcher' role.

Because the repo 'mailcatcher' no longer exists, you can't manage the original role on My Roles. That's definitely a deficiency in Galaxy. We need a process that removes roles no longer associated with a valid/existing Github repo. 

In the meantime, I removed the invalid 'Oefenweb.mailcatcher' role. You should be able to run the import now.

Here is what was in the database:

```
        name         | namespace | github_user |       github_repo        | active | is_valid
---------------------+-----------+-------------+--------------------------+--------+----------
 mailcatcher         | Oefenweb  | Oefenweb    | mailcatcher              | t      | f
 ansible-mailcatcher | Oefenweb  | Oefenweb    | ansible-mailcatcher      | t      | t
```

**Comment by tersmitten** [comment]
Thanks, the import worked now
