### ISSUE TITLE
For markdown files like README, use HTML from the GitHub API

### ISSUE THREAD

**Issue by kitsunde** [ansible/galaxy-issues#156]
A code block like:

``````
```yml
mysql_port: 3306
mysql_bind_address: "0.0.0.0"
mysql_root_db_pass: asdf1234
```
``````

End up look like:

<img width="897" alt="screenshot 2016-05-18 17 40 54" src="https://cloud.githubusercontent.com/assets/48965/15354344/b7d61402-1d1f-11e6-99ea-b708d7091451.png">

There's an extra space at the start. I.e. on: https://galaxy.ansible.com/mediapop/mysql-server/

**Comment by chouseknecht** [comment]
We should probably remove our own attempts at transforming markdown into HTML and just use the HTML directly from the GitHub API.

**Comment by chouseknecht** [comment]
This is ready for testing.  

The catalyst, as reported by @jctanner, was https://galaxy.ansible.com/api/v1/roles/?page=361. The page fails with a 500 because http://localhost:8000/kbrebanov/grafana/ throws a 500 due to the README not parsing correctly. 

The fix:
- Added a new field readme_html to the Role table.
- If readme_html is empty (old roles) then the content found in Role.readme will be parsed just as it is today. 
- If parsing fails, the Role.readme_html is updated to a message similar to the following: "Failed to parse README to HTML. Galaxy has been updated to store the HTML found in GitHub. Reimport thie role to update the README and remove this message."
- Any new imports store the HTML for README as received from GitHub in new readme_html field.

**Comment by chouseknecht** [comment]
@kitsunde do you have an example role we can test? If you re-import your role(s) in our [QA](https://galaxy-qa.ansible.com) environment, you should get a README on Galaxy that matches what you see on GitHub.

@kbrebanov Fixed your role in our [QA environment](https://galaxy-qa.ansible.com).  Built a tool that lets me re-import any role, so re-imported one of yours that was broken. See https://galaxy-qa.ansible.com/kbrebanov/grafana/.

**Comment by chouseknecht** [comment]
This is now in production.
