### ISSUE TITLE
Why does my role not contain a travis badge?

### ISSUE THREAD

**Issue by 030** [ansible/galaxy-issues#176]
http://serverfault.com/q/795370/215599

Based on [this answer](http://serverfault.com/a/795399/215599) I have decided to create an issue. According to the answerer the issue could be caused by the username, i.e. `030/ansible-sensu`. 030 interpreted by python could result in something else then 030.

**Comment by tjtoml** [comment]
Commenting to say that I am also having this issue.  
galaxy: https://galaxy.ansible.com/tjtoml/postgresql/
repo: https://github.com/tjtoml/ansible-role-postgresql  

The badge on the GitHub repo has been manually added.

**Comment by mkubenka** [comment]
This is problem with Travis `Authorization` header, for some reason they start sending wrong value so notifications API is discarding all notifications webhook requests. You can check notifications list here:

https://galaxy.ansible.com/api/v1/notifications/

Last API call was sent on 2016/08/05.

There is already issue for that on Travis GH:

https://github.com/travis-ci/travis-ci/issues/6435

**Comment by vbotka** [comment]
I see the same problem with all my roles in Galaxy. I understand, that the problem is at Travis. Just to be sure, the scenario should be:
1) git push to GitHub triggers Travis
2) Travis notifies Galaxy after testing
3) Galaxy updates repo from GitHub and updates metadata from Travis
Right? 

FYI. Under these circumstances manual import to Galaxy fails with error:
"Failed to find meta/main.yml. Must include a meta/main.yml file."

Thank you for your effort,
Cheers,

-vlado

**Comment by chouseknecht** [comment]
Travis is working again.
