### ISSUE TITLE
Fix "no ___ found" visual flicker

### ISSUE THREAD

**Issue by gregdek** [ansible/galaxy-issues#2]
When visiting a new page, there is a brief "No ___ found". It would be better to hide the screen display or show a spinner instead.

**Comment by chouseknecht** [comment]
Working on this. In the devleop branch added a loading spinner.  It's implemented on Browser Users and Browse Roles. The 'Not __ found' text no longer appears unless a search truly returns no records. While the search is happening an indicator appears in the center of the page.

**Comment by tgerla** [comment]
:+1: :100: :+1:

**Comment by chouseknecht** [comment]
Applied this to the Explore page as well.  While data is loading the 'View more...' link is hidden and a spinner appears in the middle of the table.  Each table's spinner goes away as it's data appears.  Also, discovered that numeric values coming back from the API are actually strings and not numbers. Fixed this on the client side for now so that things sort in the correct order.  Will look at fixing this in the api serializer.

**Comment by gregdek** [comment]
Love the spinner. :shipit:
