### ISSUE TITLE
Simplify ratings

### ISSUE THREAD

**Issue by gregdek** [ansible/galaxy-issues#22]
They're too complicated and too hard.

One idea: proxy directly to Github stars.

**Comment by geerlingguy** [comment]
I like the simplicity; but as with #20, make sure to think about not making one particular metric too important (or damning) for a given role.

**Comment by gregdek** [comment]
OK, so for the 1.1 release, the first step -- for both simplicity and performance reasons -- will be to compress the multiple categories of ratings to a single 5-star based rating.
1. Take all current rating data that exists and compress it into one overall rating per role;
2. Change the UI so that only the overall rating is visible.

Still thinking about the Github stars thing. :)

**Comment by gregdek** [comment]
And another possibility here: because the rating data is all in a separate table that needs to be computed in a join for every role view, we can consider adding a trigger to the rating table to compute a separate role-rating table that makes the lookup much cheaper. (performance issue)

**Comment by chouseknecht** [comment]
The structural work is done: 
-- A rating is now a simple dropdown to select a rating between 1 and 5.
-- The number of ratings and average score is stored on the role now and updated via signals

Will review this with UX early next week to clean up and maybe improve how we present the single score.

**Comment by gregdek** [comment]
Doesn't look like the ability to "rate" works for me in QA.

Steps to reproduce:
- Login to QA account with Github ID (mine is @gregdek)
- Go to Details page and click "Rate this Role," get nice pop-up
- Select the score, click "OK"
- Get the message "An unknown error occurred while trying to add your rating. Please wait a while and try again."
- Wait and try again, and get the same message mostly
- Or occasionally "you have already rated this role," even though my rating doesn't show up in the list or in the average score
- Or occasionally it just accepts it and the dialog box goes away, but my rating does not appear.

**Comment by robynbergeron** [comment]
Suggestion: Change the "Ratings" tab to say "Reviews." Because:
- There are a lot of places when you come to a page (https://45.79.141.149/detail#/role/1902, for example) that say "score" and "rating" and "ratings" and it's not clear what extra benefit one would get by clicking on that tab, because it's not the place to review. (Especially when a role doesn't yet have any reviews.)

Another suggestion: Maybe instead of Ratings: (# here) -- say # of Ratings? Just to make it clearly a different measurement than the score itself. Especially for not-english-as-primary-language speakers.

:)

**Comment by chouseknecht** [comment]
The error preventing a rating from being created is fixed.

**Comment by chouseknecht** [comment]
Good suggestion regarding 'Rating'.  Changed on Role Details, User Details and Explore pages.  Hopefully it makes it a little easier to comprehend.  In the future (maybe next release?) we will likely deprecate ratings and move to the Github star.

**Comment by robynbergeron** [comment]
I am now able to leave ratings and comments. Thanks for the improvement on rating.

Now that I am able to leave a rating and a review, the following question comes up after looking at other people's comments / ratings: 

<img width="210" alt="screen shot 2015-09-23 at 11 02 05 am" src="https://cloud.githubusercontent.com/assets/3236604/10053778/c36af006-61e2-11e5-88e1-1caab52d5ccc.png">

What on earth does "last modified" indicate? It almost reads as though there is a way to update my previous comment, but since I see multiple comments with the same exact "last modification" date ... is the "last modified" indicative of when the module was last modified, and not the comment itself? 

If there is a way to update my comment... I am not seeing it? :)

**Comment by chouseknecht** [comment]
There actually is a way to update your rating. If you click the Rating button again, it will bring up your previous rating, allowing you to make changes.  Not very intuitive.  If we decide to keep ratings, we should definitely improve this.

**Comment by robynbergeron** [comment]
Okay! This makes more sense.

This looks better now and addresses the stuff above. Thanks!

**Comment by gregdek** [comment]
Shipped!
