### ISSUE TITLE
Roles not appearing from organization

### ISSUE THREAD

**Issue by joshmoore** [ansible/galaxy-issues#252]
Similar to https://github.com/ansible/galaxy-issues/issues/245, I'm having issues getting more recent repositories to appear under "My Roles". For example:

 * https://github.com/openmicroscopy/ansible-role-omero-common/

Our workflow has been to wait until a role appears, check the import, and then to tag. Since the roles haven't appeared, I went ahead and pushed tags (trigger travis builds) which has led to several roles which I don't have access to with in correct names:

 * https://galaxy.ansible.com/openmicroscopy/ansible-role-celery-docker
 * https://galaxy.ansible.com/openmicroscopy/ansible-role-omego
 * https://galaxy.ansible.com/openmicroscopy/ansible-role-omero-web

**Comment by chouseknecht** [comment]
@joshmoore 

I think the issue is that for Galaxy to determine the repos to display on My Roles, it has to look through all the repos you have access to and decide which are 'ansible roles'. 

Because you're part of 14 organizations (I think that's what I counted on GitHub), you likely have access to hundreds repos, and Galaxy probably times out or exceeds the number of requests it can make to the GitHub API in order to get the full list.

This isn't the first time this has come, and it's something we need to address. It's not a small problem to fix on our side. The short term solution would be to create  GitHub account that is part of the `openmicroscopy` organization, and has access just to the Ansible role repose. Then, log into Galaxy with that account, and you should see the repos.

To fix the names, assuming you would like to remove `ansible` from them, you can delete the roles and re-import. Or, on My Roles, for each role, you can set the exact name the role should have when imported, and then run a fresh import.

There was a bug, that has since been fixed, where `ansible` and `role` were not being removed from the name.

**Comment by chouseknecht** [comment]
@joshmoore 

FWIW you can also use the `ansible-galaxy` command line tool to delete roles and trigger imports. I think that will work, because it sort of flips things around. It knows the name of the repo you want to work with, so it doesn't need to build a list of repos. It can query the GitHub API for the exact repo, check your access rights, and make the change.

**Comment by joshmoore** [comment]
>  Galaxy probably times out or exceeds the number of requests

Ah, understood.

>The short term solution would be to create GitHub account ...
> you can also use the ansible-galaxy command line tool to delete roles and trigger imports

I'll probably try the latter and if that fails the former, and post my results, closing this issue (I assume you have others to track the timeout).

Thanks for the info!

**Comment by joshmoore** [comment]
All my attempts to use `ansible-galaxy import` timed out. A colleague used his credentials to perform the renamings.
