### ISSUE TITLE
Github account creation only

### ISSUE THREAD

**Issue by gregdek** [ansible/galaxy-issues#39]
We really do need tighter integration with Github, since Github is already a requirement to upload roles, and should also be a requirement to rate roles and file issues against roles. It doesn't make any sense to have accounts that aren't tied to Github at this point.

First step is to disable other types of account creation; second step is to subset other account types.

**Comment by chouseknecht** [comment]
Things to note for testing:
- The sign-in workflow has been changed so that new accounts can only be created via Github. 
- There is a link 'Use an existing account not associated with Github' that allows sign-in for non-Github accounts. In the text we're indicating this will only work until 10/1/15. 
- After sign-in if the account is not associated with Github, user will be prompted to make the association.

**Comment by gregdek** [comment]
Looks good so far!

I get this copy when I try to authorize:

Authorize application
Galaxy Release by @chouseknecht would like permission to access your account

What will this say when it goes into production? Do we have an organizational GitHub key to use or something...?

**Comment by chouseknecht** [comment]
Yes. We have an 'organizational' Github key setup in production today. We will use that key in the 'new' production environment.  You won't see me in the production login, thankfully. 

We (probably me) should log into the company Github account and create a Galaxy-Dev and a Galaxy-QA application. For now it was easier to just set it up under my account, which is why you see me.

**Comment by gregdek** [comment]
Looks good to me. :shipit:
