### ISSUE TITLE
galaxy_info metadata format does not appear to be documented anywhere

### ISSUE THREAD

**Issue by wenottingham** [ansible/galaxy-issues#46]
Not on docs.ansible.com, not on galaxy.ansible.com.

**Comment by chouseknecht** [comment]
I ran across this as well while going through the process of creating a role. I was happy to find that `ansible-galaxy init` does actually provide a template meta/main.yml file with lots of helpful comments. 

Added a bunch of info on the new 'About' page with a whole section on meta/main.yml and a sample.  Please take a look on the release server  and let me know if needs more attention.

**Comment by gregdek** [comment]
Breaking out the red pen!

Second paragraph, discrete is misspelled: "A role is similar. Instead of creating giant playbooks with hundreds of tasks we can use roles to organize tasks, breaking them apart into smaller more discreet units of work."

Under "README.md", tailor is misspelled: "The init command provides a template README.md file. Taylor it to fit your role. This is your chance to provide potential users what they need to get started using the role."

Looks good to me otherwise.

**Comment by chouseknecht** [comment]
Fixed the spelling issues.

Revised the meta data section a bit.  It turns out that Ansible does not yet pull in dependencies from remote source repositories. Apparently this won't be available until v.2.

**Comment by gregdek** [comment]
Looks good to me. :+1: :shipit:
