### ISSUE TITLE
Create local galaxy mirror

### ISSUE THREAD

**Issue by RainerW** [ansible/galaxy-issues#48]
As far as i understand ansible-galaxy is closed and is an web only service. So it's not possible to create a local (offline) mirror behind a firewall? Are there plans to change this? 

Like a Maven repository the ansible galaxy is for me just as package ( roles ) distribution service. So we would need to create a local mirror / proxy which can also provide our own internal roles.

**Comment by gregdek** [comment]
You don't actually need Galaxy for this; you can specify dependencies in roles so that you can use local Git repos for this purpose. See:

http://docs.ansible.com/ansible/galaxy.html#advanced-control-over-role-requirements-files

**Comment by Eviradnus** [comment]
Using local git repositories is a real pain when dealing with dependencies.

A proper mirror would enable direct, stable, transparent (and off-line) use of dependencies, whereas local git repositories need heavy maintenance managing detailed, explicit `requirements.yml` configs (with overridden git URL + tags, pointing to these local repositories).

I reckon using a local git repository for any given role requires :
* an initial fork of the role repository as well as _all transitively required role repositories_ (could amount to a lot - and 2+ is a lot to me already) ;
* a rewrite of all the `requirements.yml` files in the dependency chain of roles ;
* when updating any role, _for each and every one of its transitive dependencies_, re-do everything (refresh the repo then tweak its deps, which cannot be automated since deps may have changed).

Unless I miss something here, one cannot actually say local git repositories are equivalent to a mirror.

I'd really like having a clever, standard way to mirror the central Galaxy, without having to wait for [someone else](https://www.jfrog.com/jira/browse/RTFACT-12695) to provide this feature...
