### ISSUE TITLE
confirm email with github account still says AnsibleWorks in the subject header

### ISSUE THREAD

**Issue by jlmitch5** [ansible/galaxy-issues#52]
To reproduce:
-Click "Log into Galaxy with GitHub"

The confirmation email that is sent includes the heading;
AnsibleWorks Galaxy Confirm E-Mail Address

**Comment by chouseknecht** [comment]
Done.

**Comment by gregdek** [comment]
Looks like @robynbergeron tested this and it took her to the production Galaxy server at time of Github connection, which obviously still gives the outdated copy. Is this just because of different API keys? Any way to test this on the QA server end-to-end?

**Comment by robynbergeron** [comment]
Annnd I just retested this and now it works. Not sure what happened, or if I'm just incapable of using an incognito window correctly and consistently :)

**Comment by chouseknecht** [comment]
I confirmed this is working as expected in QA.  The email text does in the first paragraph give the site name as galaxy.ansible.com.  That's OK.  The actual link to confirm the email points to the QA server - which is what we care about.  And 'AnsibleWorks' is gone 

Here's the text I received:

You are receiving this email because someone (hopefully you) created an account at https://galaxy.ansible.com. To confirm this is correct, please click on the following link to verify your email address:

https://45.79.141.149/accounts/confirm-email/jsoewkgbh79cb3wfxj4gkevrmafdqrfcbzptessiyznjncmdlx5rgpxxxacuckk5/

If you believe you have received this email in error, please disregard it.

If you have any questions regarding this email, or if you have trouble with the link provided above, please contact us at support@ansible.com.

Thanks!

The Ansible Team

**Comment by robynbergeron** [comment]
This is now working for me as well. :)

**Comment by gregdek** [comment]
Shipped!
