### ISSUE TITLE
Replacing categories with tags

### ISSUE THREAD

**Issue by gregdek** [ansible/galaxy-issues#56]
This would imply:
- Allowing users to include arbitrary tags in role metadata;
- Changing search to accept arbitrary tags;
- Showing tag clouds instead of predefined category sidebars;
- Search would then do matching in role name, role tags, role description
- Change of import mechanisms?

This whole thing might not fit into 1.1, but we'll align it against 1.1 anyway and see how far we get. :)

**Comment by chouseknecht** [comment]
Everything is done with the exception of changing the template meta/main.yml file generated by ansible-galaxy.

**Comment by gregdek** [comment]
Also need to change docs here:

https://45.79.141.149/intro#create-role

...need to replace "categories" with "tags" where it shows up.

(actually, not yet -- going to change docs when new galaxy client is released.)

**Comment by gregdek** [comment]
Test plan:
- Upload something with categories
- Upload something with tags
- Upload something with categories and tags
- Upload something with A LOT of tags (more than 20, which I think is some kind of limit?)
- Upload README files with HTML (and ensure that it gets stripped)
- Fuzz testing of tag/category inputs
- Reimport of something with tags (reimport should work same as fresh import?)
- Test colon delimiter (cloud:aws should become two tags, for example)
- Test uploading "ooboontoo" as a tag, then replace "ooboontoo" with "ubuntu" and reuploading
- Test different delimiters
- Test invalid dependency syntax

**Comment by gregdek** [comment]
Yeah, currently failing imports because of:

ERROR:  Failed to add role: global name 'instanice' is not defined

Perhaps you meant "instance" somewhere. In any case, we can't test further. :)

**Comment by chouseknecht** [comment]
This is fixed with the latest code push.

**Comment by robynbergeron** [comment]
Okay. Here's what I tested:
- Created a new role - https://45.79.141.149/detail#/role/5190  with: https://github.com/ansibull/ansible-role-pimpmylog/commit/c6adb0efe29cbd697c1de103ed8a028567bc11c1#diff-9b4ddf055111f4371f04fbb8b5366655

(Note that this version has tags, and not categories, in meta/main.yml)
- Imported role to galaxy - list of tags / categories did not show up under tags section on the role page in galaxy.
- Tried reimporting. Didn't change
- Edited role in meta/main.yml to say categories: instead of tags: -- reimported role -- now the tags show up.

My understanding was that either tags or categories would get imported and show up as tags on the page either way. Looks like maybe categories is still the only thing getting imported. (Maybe this is intended? not sure.)

I think @gregdek is looking at a case where he has a role with both tags and categories listed, so seeing what he's up to with that.

**Comment by gregdek** [comment]
Yep. I'm also seeing all imports with categories: working, and all imports with tags: silently ignoring.

**Comment by gregdek** [comment]
Ah, right: we changed "tags" to "galaxy_tags" in the metadata. Retesting.

**Comment by gregdek** [comment]
OK, so both "categories" and "galaxy_tags" work in latest testing. Will keep banging on corner cases.

**Comment by gregdek** [comment]
Limit appears to be 19 tags, which is fine, might consider documenting somewhere.

**Comment by gregdek** [comment]
Also strips HTML appropriately.

**Comment by gregdek** [comment]
Tags with colons are now split into two tags. Any other weird symbols (notably including unicode) cause a tag to be ignored. That may be ok for now.

**Comment by gregdek** [comment]
OK, I'm satisfied that this works as expected.

**Comment by gregdek** [comment]
Shipped!
