### ISSUE TITLE
Use GitHub username for roles instead of the Galaxy one

### ISSUE THREAD

**Issue by ktriponis** [ansible/galaxy-issues#64]
While it used to be a nice to be able to create a username on galaxy, I feel like it becomes quite misleading due to Galaxy dropping users. "Starting January 1, 2016 Galaxy will only support Github authentication."

Currently I have a Galaxy user that is linked with my GitHub account and is totally different. The sad part is that if I create a role my Galaxy username is used instead of the GitHub name where the role actually resides.

All this leads to a couple of problems:
1. I can upload roles that I don't have any access to and have nothing to do with by just specifying their GitHub account name and repo allowing for duplicate roles in galaxy. Which is why username for the added role should be taken from GitHub acc ant not from Galaxy.
2. It locks in my GitHub account to my galaxy name. Since unlinking GitHub from Galaxy is not really possible, I am left with whatever Galaxy name I picked and that can be rather troublesome if someone links incorrect GitHub account with incorrect user.
3. I'm not sure what would happen, but what if someone at some point would create a GitHub account with a name that matches my Galaxy account and tried to link it with Galaxy? It seems like they'd be up for a surprise not being able to claim their name and publishing their roles using their actual GitHub account. Not to mention organizations which have a GitHub account would be forced to use some alien name to publish roles for their products which would diminish the trust from users that would want to use the role in preference of the imposers (who might not even be affiliated with the company) role.

**Comment by gregdek** [comment]
Thanks for the comments, @ktriponis. 
1. Galaxy is very dependent upon Github, and as we look to make more improvements -- making it easy for users to fork Galaxy roles, etc. -- it makes sense to strengthen that tie explicitly.  The use case of "uploading someone else's roles" isn't really a use case we should be supporting, we've determined; because Github makes it easy to fork, the proper path should be for a user to fork the role and upload it themselves under their own account.  That way, we have a strong guarantee that people who have uploaded roles also have the power and responsibility to maintain them.

2 and 3. One of the reasons we're taking so much time in the transition here is to sort out cases like this, and to come up with ways to help users with this migration. The goal is to have a 1-to-1 relationship between Galaxy and Github users. This is the first step towards that goal.

**Comment by gregdek** [comment]
And you're right, the role namespacing problem now becomes acute. We don't have the right answer for it -- yet.

**Comment by srgvg** [comment]
FYI - please keep in mind people might want to upload roles from an organisation.
I especially create a Galaxy username that matched my company's name, which makes more sense here.

If the namespace needs to be tied to what one has access to on Github, keep in mind not only the Github username is relevant, but also several organisations!

**Comment by gregdek** [comment]
Yep. It's becoming very clear to us that "uploader for organization" is a key use case. We'll be having a design session soon to work through the ramifications of this.

**Comment by bborysenko** [comment]
it will be great feature, and it's what exactly most companies need. For the moment it's not clear how we can link Github organization to Galaxy account

**Comment by shrikeh** [comment]
One of the problems I've encountered now is that - to stop my Github full of `ansible-*` repos, I moved them all off into a new organization which I called `ansible-shrikeh-roles`. This was fine, however I've gone back after a break from ansible and now the Github org name is the name of the user - yet it is my account.

Is there any way that these two possibilities can coincide? I don't think it's edge case that a company might have a specific organisation for all of the public repos, but want the Galaxy username to be used.

**Comment by ssbarnea** [comment]
Some time ago I created a specific github organization for putting Ansible roles: https://github.com/ansiblers

My intent was to gather a bunch of people and manage common roles via this organisation but I got too busy to drive this. Who know maybe someone from here is interested about joining.
